#pragma kernel Verlet
#pragma kernel DensityPressure
#pragma kernel Force
#pragma kernel HandInput
#pragma kernel PickNewParticles
#pragma kernel CopyAppendToRW

struct GPUParticle {
     float3 position;
     float  density;
     float3 velocity;
     float  pressure;
     float3 force;
     //float  temperature;
     uint   type; // 0 = water, 1 = fire, 2 = wood, 3 = earth, 4 = metal, 5 = seed
     float  temperature;
     float  remainingLifetime;
     float  pad0;
     float  pad1;
};

struct NeighborsInfo {
    int startIndex;
    int count;
};

  //StructuredBuffer<GPUParticle> lastParticles;
//RWStructuredBuffer<GPUParticle> nextParticles;
  StructuredBuffer<NeighborsInfo> neighborInfo;
  StructuredBuffer<int> neighborLists;
  StructuredBuffer<GPUParticle> lastParticles;
RWStructuredBuffer<GPUParticle> particles;
AppendStructuredBuffer<GPUParticle> nextParticles;

int particleCount;

float pi = 3.14159274;

// particle physical properties (move to per-particle buffer?)
float particleMass           = 0.02;
float wallDamping; 
float particleStiffness      = 2000.0; 
float particleRestingDensity = 1000.0;
float particleViscosity      = 1000.0;

float boundsSize;

float smoothingLength = 0.020;
float interactionLength;
float timeStep = 0.01666;
float3 gravity = float3(0, -9.82, 0);

float3 leftHandPosition;
int    leftHandMode; 
float  leftHandStrength;
float3 rightHandPosition;
int    rightHandMode;
float  rightHandStrength;

float rand (float n) {
    return frac(sin(n) * 43758.5453123);
}

[numthreads(128,1,1)]
void Verlet (uint id : SV_DispatchThreadID) {
    if (id >= particleCount)
        return;

    GPUParticle thisParticle = particles[id]; 
    float3 acceleration = thisParticle.force / thisParticle.density;
    float3 velocity = thisParticle.velocity + timeStep * acceleration;// + timeStep * gravity;
    
    if (thisParticle.type == 3 || thisParticle.type == 4) {
        velocity = float3(0,0,0);
    } else if (thisParticle.type == 2) { 
        velocity *= 0.10;
    }
    
    float3 position = thisParticle.position + timeStep * velocity; 
    //velocity *= 0.985;

    // TODO: apply sphere constraint
    if (length(position) > boundsSize) {
        position = normalize(position) * boundsSize;
        //velocity -= normalize(position) * particleRadius;
        velocity *= wallDamping;
    }
    
    particles[id].velocity = velocity;
    particles[id].position = position;
}

[numthreads(128,1,1)]
void DensityPressure(uint id : SV_DispatchThreadID) {
    if (id >= particleCount)
        return;

    GPUParticle thisParticle = particles[id];
    float densitySum = 0.0;
    
    // TODO: optimize!!! needs spatial partitioning
    //for (uint j = 0; j < neighborInfo[id].count; j++) {
    //    uint i = neighborLists[neighborInfo[id].startIndex + j];
    for (uint i = 0; i < particleCount; i++) {
        GPUParticle otherParticle = particles[i];
        float3 delta = thisParticle.position - otherParticle.position;
        float distance = length(delta);
        if (distance < smoothingLength) {
            densitySum += particleMass * 315.0 * pow(smoothingLength * smoothingLength - distance * distance, 3.0) / (64.0 * pi * pow(smoothingLength, 9.0));
        }
        
        if (distance < interactionLength) {
            // you'd think this would be a divergence madhouse but it's still much faster than CPU implementation
            if (thisParticle.type == 1/* && distance < interactionLength*/) {
                if (otherParticle.type == 2) {
                    //particles[i].temperature += 0.5;
                    //if (particles[i].temperature > 1) {
                        otherParticle.type = 1;
                        otherParticle.remainingLifetime = 1.0;
                    //} 
                    particles[i] = otherParticle;
                }
                
                if (otherParticle.type == 0) {
                    //thisParticle.type = 0;
                    thisParticle.remainingLifetime -= 0.5;
                    otherParticle.velocity *= 1.5;
                    particles[i] = otherParticle;
                } 
            }
            
            if (thisParticle.type == 2/* && distance < interactionLength*/) {
                if (otherParticle.type == 0) {
                    //particles[i].type = 2;
                    //otherParticle.remainingLifetime = -5.0;
                    otherParticle.type = 2;
                    thisParticle.remainingLifetime += 0.25;
                    particles[i] = otherParticle;
                }
            }
            
            if (thisParticle.type == 5/* && distance < interactionLength*/) {
                if (otherParticle.type == 3) {
                    thisParticle.type = 2;
                    thisParticle.remainingLifetime += 3.0;
                }
            }
        }
    }
    
    thisParticle.density = densitySum;
    thisParticle.pressure = max(particleStiffness * (densitySum - particleRestingDensity), 0.0);
    particles[id] = thisParticle;
}

// TODO: could this be rolled into DensityPressure kernel? avoid calculating delta twice etc
[numthreads(128,1,1)]
void Force(uint id : SV_DispatchThreadID) {
    if (id >= particleCount)
        return;

    GPUParticle thisParticle = particles[id];
    float3 pressureForce = float3(0,0,0);
    float3 viscosityForce = float3(0,0,0);

    //for (uint j = 0; j < neighborInfo[id].count; j++) {
    //    uint i = neighborLists[neighborInfo[id].startIndex + j];
    for (uint i = 0; i < particleCount; i++) {
        if (id == i) continue;
        float3 delta = thisParticle.position - particles[i].position;
        float distance = length(delta);
        if (distance < smoothingLength) {
            pressureForce -= particleMass * (thisParticle.pressure + particles[i].pressure) / (2.0 * particles[i].density) *
                -45.0 / (pi * pow(smoothingLength, 6.0)) * pow(smoothingLength - distance, 2.0) * normalize(delta);
                
            viscosityForce += particleMass * (particles[i].velocity - thisParticle.velocity) * particles[i].density *
                 45.0 / (pi * pow(smoothingLength, 6.0)) * (smoothingLength - distance);
        }
    }
    
    viscosityForce *= particleViscosity;
    if (length(viscosityForce) > 50.0)
        viscosityForce = normalize(viscosityForce) * 50.0;
        
    if (thisParticle.type == 1) {
        gravity = -gravity;
    }
        
    float3 externalForce = gravity * thisParticle.density;
    
    particles[id].force = pressureForce + viscosityForce + externalForce;
}

[numthreads(128,1,1)]
void HandInput(uint id : SV_DispatchThreadID) {
    if (id >= particleCount)
        return;

    GPUParticle thisParticle = particles[id];

    // mode enum: 0 = none, 1 = fist, 2 = point (water), 3 = point (fire), 4 = point (wood)
    // type enum: 0 = water, 1 = fire, 2 = wood, 3 = earth, 4 = metal, 5 = seed
    float3 leftHandDelta = thisParticle.position - leftHandPosition;
    float leftHandDist = length(leftHandDelta);
    if (leftHandMode == 1) {
        thisParticle.force -= (leftHandDelta * 5.0) / pow(leftHandDist, 2.0); // * thisParticle.density?
    } else if (leftHandMode >= 2 && leftHandMode <= 6 && leftHandDist < leftHandStrength * 0.35f) {
    /*
        if (leftHandMode == 2) {
            thisParticle.type = 0;
        } else if (leftHandMode == 3) {
            thisParticle.type = 1;
        } else if (leftHandMode == 4) {
            thisParticle.type = 2;
        }
        */
    }
    
    float3 rightHandDelta = thisParticle.position - rightHandPosition;
    float rightHandDist = length(rightHandDelta);
    if (rightHandMode == 1) {
        thisParticle.force -= (rightHandDelta * 5.0) / pow(rightHandDist, 2.0); // * thisParticle.density?
    } else if (rightHandMode >= 2 && rightHandMode <= 6 && rightHandDist < rightHandStrength * 0.35f) {
    /*
        if (rightHandMode == 2) {
            thisParticle.type = 0;
        } else if (rightHandMode == 3) {
            thisParticle.type = 1;
        } else if (rightHandMode == 4) {
            thisParticle.type = 2;
        }
        */
    }
    
    particles[id] = thisParticle;
}

[numthreads(128,1,1)]
void PickNewParticles(uint id : SV_DispatchThreadID) {
    if (id >= particleCount)
        return;
        
    GPUParticle thisParticle = particles[id];
    
    if (thisParticle.type == 1 || thisParticle.type == 5) {
        thisParticle.remainingLifetime -= timeStep / 2.0;
    } else if (thisParticle.type == 2) {
        thisParticle.remainingLifetime -= timeStep / 7.5;
        if (thisParticle.remainingLifetime > 3.0) {
            GPUParticle newWoodParticle = particles[id];
            newWoodParticle.remainingLifetime = thisParticle.remainingLifetime - 2.0;
            newWoodParticle.position = thisParticle.position + float3(
                (rand(thisParticle.position.x) - 0.5) / 20.0,
                (rand(thisParticle.position.y) - 0.5) / 20.0 + (1.0/50.0),
                (rand(thisParticle.position.z) - 0.5) / 20.0 
            );
            nextParticles.Append(newWoodParticle);
            thisParticle.remainingLifetime = 1.0;
        }
    }// else {
    //    thisParticle.remainingLifetime -= timeStep / 30.0;
    //}

    if (thisParticle.remainingLifetime > 0.0) {
        nextParticles.Append(thisParticle);
    }
}

[numthreads(128,1,1)]
void CopyAppendToRW(uint id : SV_DispatchThreadID) {
    if (id >= particleCount)
        return;
        
    GPUParticle thisParticle = lastParticles[id];
    particles[id] = thisParticle;
}
